# MUST EDIT BELOW
sitename: _layouts       #Your site title
tagline: themes for jekyll  #You should always have a tagline
url: http://www.layouts-the.me   #URL Please
ga: UA-61203-14             #Google Analytics ID
sitemap: VCjPu4enLtZl8QXpuPVxY6vMufxe68UrchkhHkzz1zA    #Google webmaster verification code
# END
# CHOOSE YOUR PREFERENCE
pygments:    true
markdown:    maruku
permalink:   pretty
# END
exclude: LICENSE, README.markdown, Rakefile
