#Presentation Settings
sitename: _layouts
tagline: themes for jekyll
#Deployment  Settings
pygments:    false
markdown:    kramdown
permalink:   pretty
kramdown:
  auto_ids: false
exclude: LICENSE, README.markdown
ftp_host: studiomohawk.com
ftp_dir: /www/layouts
