#Presentation Settings
sitename: _layouts
tagline: themes for jekyll
url: http://layouts.studiomohawk.com
#Deployment  Settings
pygments:    true
markdown:    kramdown
permalink:   pretty
kramdown:
  auto_ids: false
exclude: LICENSE, README.markdown
ftp_host: studiomohawk.com
ftp_dir: /www/layouts
