#Presentation Settings
sitename: _layouts
tagline: themes for jekyll
#Development Settings
pygments:    false
markdown:    kramdown
permalink:   pretty
kramdown:
  auto_ids: false
#Deployment  Settings
ftp_host: studiomohawk.com
ftp_dir: /www/layouts
